[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc_version = '0.8.20'
evm_version = 'paris'

[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
